package mx.com.desivecore.commons.constants;

public enum PermissionEnum {
	
	BRANCH, 
	ROLE, 
	USER, 
	PRODUCT,
	SUPPLIER,
	CLIENT,
	REMISSION_ENTRY_GENERAL,
	REMISSION_ENTRY_OPERATIONAL,
	PRODUCT_TAG,
	SECURITY_DATA_SHEET,
	CERTIFICATE,
	REMISSION_OUTPUT,
	INVENTORY_REPORT,
	REMISSION_ENTRY_REPORT,
	REMISSION_OUTPUT_REPORT, 
	QUOTE,
	RETURN_RE,
	RETURN_RO,
	QUARANTINE,
	CASH_OPERATIONAL,
	CASH_MANAGMENT
	;

}
